module.exports.raw = {
  assignment: [   
    '<tr class="odd"><td scope="row" colspan="2">09/08/17</td><td class="nWp"><a id="showAssignmentInfo" name="showAssignmentInfo" data-sid="74872" data-gid="1633625" data-aid="1566435" data-pos="right" data-type="default" data-maxheight="550" data-minwidth="400" data-maxwidth="450" data-title="Assignment Details" href="javascript:void(0)">Participation</a></td><td class="nWp">100&nbsp;&nbsp;</td><td class="aRt">100.00</td><td class="aRt">100 <span style="font-size:x-small;">out of</span> 100</td><td>&nbsp;</td><td>&nbsp;</td><td class="nWp">&nbsp;</td></tr>',
    '<tr class="even"><td scope="row" colspan="2">10/12/17</td><td class="nWp"><a id="showAssignmentInfo" name="showAssignmentInfo" data-sid="74872" data-gid="1637489" data-aid="1815551" data-pos="right" data-type="default" data-maxheight="550" data-minwidth="400" data-maxwidth="450" data-title="Assignment Details" href="javascript:void(0)">Developing a Research Question</a></td><td class="nWp">100&nbsp;&nbsp;</td><td class="aRt">100.00</td><td class="aRt">100 <span style="font-size:x-small;">out of</span> 100</td><td>&nbsp;</td><td>&nbsp;</td><td class="nWp">School Activity-SCHL BOARD</td></tr>',
    '<tr class="odd"><td scope="row" colspan="2">10/04/17</td><td class="nWp"><a id="showAssignmentInfo" name="showAssignmentInfo" data-sid="74872" data-gid="1622702" data-aid="1782162" data-pos="right" data-type="default" data-maxheight="550" data-minwidth="400" data-maxwidth="450" data-title="Assignment Details" href="javascript:void(0)">General Dollar</a></td><td class="nWp"><a id="specCode_74872_1782162" name="specCode_74872_1782162" style="padding-left:2px" alt="View special code" tooltip="View special code" data-pos="left" data-info="Excused" href="javascript:void(0)"><img src="qfileloader.p?file=info_24.png&amp;rev=0101790517100008" id="dlKkjcTczebfdlfe" name="dlKkjcTczebfdlfe" style="width:16px;height:16px" alt="special code"></a>&nbsp;</td><td>&nbsp;</td><td tooltip="This assignment is not graded" class="aRt">* <span style="font-size:x-small;">out of</span> 100</td><td>&nbsp;</td><td tooltip="This assignment is marked no count" class="aCt"><img src="qfileloader.p?file=green-checkmark.png&amp;rev=0101790517100008" id="jiobShjjAdlbhaib" name="jiobShjjAdlbhaib" style="width:15px;height:15px" alt="No count"></td><td class="nWp">&nbsp;</td></tr>',
    '<tr class="odd"><td scope="row" colspan="2">09/15/17</td><td class="nWp"><a id="showAssignmentInfo" name="showAssignmentInfo" data-sid="74872" data-gid="1621766" data-aid="1574664" data-pos="right" data-type="default" data-maxheight="550" data-minwidth="400" data-maxwidth="450" data-title="Assignment Details" href="javascript:void(0)">TEST 1</a></td><td class="nWp">93<a id="specCode_74872_1574664" name="specCode_74872_1574664" style="padding-left:2px" alt="View special code" tooltip="View special code" data-pos="left" data-info="Automated Drop Score" href="javascript:void(0)"><img src="qfileloader.p?file=info_24.png&amp;rev=0101790517100008" id="laCbHCkbliccbaCh" name="laCbHCkbliccbaCh" style="width:16px;height:16px" alt="special code"></a>&nbsp;</td><td class="aRt">93.00</td><td class="aRt">93 <span style="font-size:x-small;">out of</span> 100</td><td>&nbsp;</td><td tooltip="This assignment is marked no count" class="aCt"><img src="qfileloader.p?file=green-checkmark.png&amp;rev=0101790517100008" id="ivBijiafQoRpkdbg" name="ivBijiafQoRpkdbg" style="width:15px;height:15px" alt="No count"></td><td class="nWp">School Activity-SCHL BOARD</td></tr>'
  ],
  banner: [
    '<tr style="font-weight:bold;line-height:1.3em; background-color:#EAEEF4" class=""><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="1st Citizenship Grade">PC1</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="1st Term Grade">PR1</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="2nd Citizenship Grade">PC2</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="2nd Term Grade">PR2</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="3rd Citizenship Grade">QC1</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="3rd Term Grade">Q1</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="4th Citizenship Grade">PC3</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="4th Term Grade">PR3</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="5th Citizenship Grade">PC4</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="5th Term Grade">PR4</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="6th Citizenship Grade">QC2</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="6th Term Grade">Q2</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="1st SemExam Grade">SE1</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="1st Semester Grade">S1</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="7th Citizenship Grade">PC5</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="7th Term Grade">PR5</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="8th Citizenship Grade">PC6</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="8th Term Grade">PR6</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="9th Citizenship Grade">QC3</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="9th Term Grade">Q3</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="10th Citizenship Grade">PC7</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="10th Term Grade">PR7</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="11th Citizenship Grade">PC8</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="11th Term Grade">PR8</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="12th Citizenship Grade">QC4</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="12th Term Grade">Q4</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="2nd SemExam Grade">SE2</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="2nd Semester Grade">S2</span></td></tr>',
    '<tr style="font-weight:bold;line-height:1.3em; background-color:#EAEEF4" class=""><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="1st Semester Grade">S1</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="2nd Semester Grade">S2</span></td></tr>',
    '<tr style="font-weight:bold;line-height:1.3em; background-color:#EAEEF4" class=""><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="1st Midterm Grade">PR1</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="1st Citizenship Grade">C1</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="1st Term Grade">MP1</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="3rd Citizenship Grade">PC2</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="2nd Midterm Grade">PR2</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="4th Citizenship Grade">C2</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="2nd Term Grade">MP2</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="5th Citizenship Grade">PC3</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="3rd Midterm Grade">PR3</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="6th Citizenship Grade">C3</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="3rd Term Grade">MP3</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="1st SemExam Grade">SE1</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="1st Semester Grade">S1</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="7th Citizenship Grade">PC4</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="4th Midterm Grade">PR4</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="8th Citizenship Grade">C4</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="4th Term Grade">MP4</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="9th Citizenship Grade">PC5</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="5th Midterm Grade">PR5</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="10th Citizenship Grade">C5</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="5th Term Grade">MP5</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="11th Citizenship Grade">PC6</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="6th Midterm Grade">PR6</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="12th Citizenship Grade">C6</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="6th Term Grade">MP6</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="2nd SemExam Grade">SE2</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="2nd Semester Grade">S2</span></td><td style="white-space:nowrap;vertical-align:bottom"><span tooltip="Final Grade">AV</span></td></tr>',
  ],
  cat: [
    '<tr class="sf_Section cat"><td scope="row" class="nPd noRBdr" style="width:5px;background-color:#9999FF !important">&nbsp;</td><td class="nWp noLBdr" style="padding:0px 0px 0px 2px !important;background-color:#C9D6E4 !important;font-weight:bold !important" colspan="2">PE Health Athletics<br><span class="fIl fWn fXs">weighted at 100.00%</span></td><td class="bld" style="background-color:#C9D6E4 !important">100</td><td class="bld aRt" style="background-color:#C9D6E4 !important">100.00</td><td class="bld nWp aRt" style="background-color:#C9D6E4 !important">100 <span class="fXs">out of</span> 100</td><td style="background-color:#C9D6E4 !important" colspan="3">&nbsp;</td></tr>',
    '<tr class="sf_Section cat"><td scope="row" class="nPd noRBdr" style="width:5px;background-color:#FFCCCC !important">&nbsp;</td><td tooltip="The weight of category Major has been adjusted to 0%, since it does not have any graded assignments" class="nWp noLBdr" style="padding:0px 0px 0px 2px !important;background-color:#C9D6E4 !important;font-weight:bold !important" colspan="2">Major<br><span class="fIl fWn fXs">weighted at 60.00%, adjusted to 0.00%</span></td><td class="bld" style="background-color:#C9D6E4 !important">&nbsp;</td><td class="bld aRt" style="background-color:#C9D6E4 !important">&nbsp;</td><td class="bld nWp aRt" style="background-color:#C9D6E4 !important">&nbsp;</td><td style="background-color:#C9D6E4 !important" colspan="3">&nbsp;</td></tr>',
    '<tr class="sf_Section cat"><td scope="row" class="nPd noRBdr" style="width:5px;background-color:#FFFFCC !important">&nbsp;</td><td class="nWp noLBdr" style="padding:0px 0px 0px 2px !important;background-color:#C9D6E4 !important;font-weight:bold !important" colspan="2">Homework </td><td class="bld" style="background-color:#C9D6E4 !important">&nbsp;</td><td class="bld aRt" style="background-color:#C9D6E4 !important">&nbsp;</td><td class="bld nWp aRt" style="background-color:#C9D6E4 !important">&nbsp;</td><td style="background-color:#C9D6E4 !important" colspan="3">&nbsp;</td></tr>'
  ],
  course: [
    '<tr style="background-color:#EAEEF4" class="even"><td scope="row"><a id="aEkddaUitadclpzp" name="aEkddaUitadclpzp" href="javascript:void(0)">IND STUDY TECH APP 1</a></td><td style="white-space:nowrap">1 - 4</td></tr>',
    '<tr style="background-color:#FFFFFF" class="even"><td scope="row"><a id="Ocjjjdkxlikbhjkb" name="Ocjjjdkxlikbhjkb" href="javascript:void(0)">CHEMISTRY 1 PreAP-GT</a></td><td style="white-space:nowrap">1 - 6</td></tr>',
    '<tr style="background-color:#FFFFFF" class="even"><td scope="row"><a id="VAaljwYodbclbdfu" name="VAaljwYodbclbdfu" href="javascript:void(0)">ENGLISH 3</a></td><td style="white-space:nowrap">1 - 2</td></tr>',
    '<tr style="background-color:#FFFFFF" class="even"><td scope="row">ATH-CC-B 1A</td><td style="white-space:nowrap">1 - 3</td></tr>',
    '<tr style="background-color:#EAEEF4" class="even"><td scope="row">ENGLISH 1 PreAP</td><td style="white-space:nowrap">1 - 3</td></tr>',
    '<tr style="background-color:#FFFFFF" class="even"><td scope="row">WORLD GEOG PreA</td><td style="white-space:nowrap">1 - 6</td></tr>'
  ],
  lit: [
    '<tr class="sf_Section cat"><td scope="row" class="nPd noRBdr" style="width:5px;background-color:#FFFFCC !important">&nbsp;</td><td class="nWp noLBdr" style="padding:0px 0px 0px 2px !important;background-color:#C9D6E4 !important;font-weight:normal !important" colspan="2"><span tooltip="The dates for Q2 (Term 6) are 10/17/2017 - 12/21/2017">Q2</span><span class="fIl fWn fXs"> (weighted at 10.00%)</span></td><td class="bld" style="background-color:#C9D6E4 !important">100</td><td class="bld aRt" style="background-color:#C9D6E4 !important">100.00</td><td class="bld nWp aRt" style="background-color:#C9D6E4 !important">1000 <span class="fXs">out of</span> 1000</td><td style="background-color:#C9D6E4 !important" colspan="3">&nbsp;</td></tr>',
    '<tr class="sf_Section cat"><td scope="row" class="nPd noRBdr" style="width:5px;background-color:#FFCCCC !important">&nbsp;</td><td class="nWp noLBdr" style="padding:0px 0px 0px 2px !important;background-color:#C9D6E4 !important;font-weight:normal !important" colspan="2"><span tooltip="The dates for Q2 (Term 6) are 10/17/2017 - 12/21/2017">Q2</span><span class="fIl fWn fXs"> (weighted at 70.00%)</span></td><td class="bld" style="background-color:#C9D6E4 !important">92</td><td class="bld aRt" style="background-color:#C9D6E4 !important">91.67</td><td class="bld nWp aRt" style="background-color:#C9D6E4 !important">275 <span class="fXs">out of</span> 300</td><td style="background-color:#C9D6E4 !important" colspan="3">&nbsp;</td></tr>',
    '<tr class="sf_Section cat"><td scope="row" class="nPd noRBdr" style="width:5px;background-color:#CCFFFF !important">&nbsp;</td><td class="nWp noLBdr" style="padding:0px 0px 0px 2px !important;background-color:#C9D6E4 !important;font-weight:normal !important" colspan="2"><span tooltip="The dates for Q2 (Term 6) are 10/17/2017 - 12/21/2017">Q2</span><span class="fIl fWn fXs"> (weighted at 40.00%)</span></td><td class="bld" style="background-color:#C9D6E4 !important">100</td><td class="bld aRt" style="background-color:#C9D6E4 !important">99.50</td><td class="bld nWp aRt" style="background-color:#C9D6E4 !important">995 <span class="fXs">out of</span> 1000</td><td style="background-color:#C9D6E4 !important" colspan="3">&nbsp;</td></tr>'
  ],
  strip: [
    '<tr style="background-color:#EAEEF4" class="even"><td style="white-space:nowrap">99</td><td style="white-space:nowrap">E</td><td style="white-space:nowrap">98</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">98</td><td style="white-space:nowrap">E</td><td style="white-space:nowrap">95</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">100</td><td style="white-space:nowrap">E</td><td style="white-space:nowrap">100</td><td style="white-space:nowrap">99</td><td style="white-space:nowrap">98</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">89</td><td style="white-space:nowrap">E</td><td style="white-space:nowrap">100</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">100</td><td style="white-space:nowrap">E</td><td style="white-space:nowrap">100</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">99</td><td style="white-space:nowrap">E</td><td style="white-space:nowrap">100</td><td style="white-space:nowrap">X</td><td style="white-space:nowrap">100</td><td style="white-space:nowrap">&nbsp;</td></tr>',
    '<tr style="background-color:#FFFFFF" class="even"><td style="white-space:nowrap">85</td><td style="white-space:nowrap">94</td></tr>',
    '<tr style="background-color:#FFFFFF" class="even"><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">&nbsp;</td><td style="white-space:nowrap">100</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td><td tooltip="This Grade Bucket was not used during this Class">&nbsp;</td></tr>'
  ],
  year: [
    '<tr style="font-weight:bold;line-height:1.3em; background-color:#FFFFFF" class=""><td scope="row" style="border-right:none; border-top:thin solid; border-bottom:thin solid"><div style="width:1px;overflow:visible;white-space:nowrap;">2017 - 2018, Grade 11</div></td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td></tr>',
    '<tr style="font-weight:bold;line-height:1.3em; background-color:#FFFFFF" class=""><td scope="row" style="border-right:none; border-top:thin solid; border-bottom:thin solid"><div style="width:1px;overflow:visible;white-space:nowrap;">2016 - 2017, Grade 10</div></td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td></tr>',
    '<tr style="font-weight:bold;line-height:1.3em; background-color:#FFFFFF" class=""><td scope="row" style="border-right:none; border-top:thin solid; border-bottom:thin solid"><div style="width:1px;overflow:visible;white-space:nowrap;">2016 - 2017, Grade 10</div></td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td></tr>'
  ],
  other: [
    '<tr class="odd"><td scope="row" class="fIl nWp" colspan="9">There are no Major assignments</td></tr>',
    '<tr class="odd"><td scope="row" class="fIl nWp" colspan="9">There are no Homework  assignments</td></tr>',
    '<tr class="odd"><td scope="row" class="fIl nWp" colspan="9">There are no Major assignments</td></tr>',
    '<tr style="font-weight:bold;line-height:1.3em; background-color:#EAEEF4" class=""><td scope="row" style="vertical-align:bottom">Class</td><td style="vertical-align:bottom">Terms</td></tr>',
    '<tr style="font-weight:bold;line-height:1.3em; background-color:#EAEEF4" class=""><td scope="row" style="vertical-align:bottom">Class</td><td style="vertical-align:bottom">Terms</td></tr>',
    '<tr style="font-weight:bold;line-height:1.3em; background-color:#EAEEF4" class=""><td scope="row" style="vertical-align:bottom">Class</td><td style="vertical-align:bottom">Terms</td></tr>',
    '<tr style="font-weight:bold;line-height:1.3em; background-color:#FFFFFF" class=""><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td><td style="border-right:none; border-top:thin solid; border-bottom:thin solid">&nbsp;</td></tr>'
  ]
}

module.exports.data = {
  assignment: [
    {"assignments": {"date": "09/08/17", "meta": {"absent": "&nbsp;", "missing": "&nbsp;", "noCount": false}, "score": {"earned": 100, "total": 100}, "title": "Participation"}},
    {"assignments": {"date": "10/12/17", "meta": {"absent": "School Activity-SCHL BOARD", "missing": "&nbsp;", "noCount": false}, "score": {"earned": 100, "total": 100}, "title": "Developing a Research Question"}},
    {"assignments": {"date": "10/04/17", "meta": {"absent": "&nbsp;", "missing": "&nbsp;", "noCount": true}, "score": {"earned": "*", "total": 100}, "title": "General Dollar"}},
    {"assignments": {"date": "09/15/17", "meta": {"absent": "School Activity-SCHL BOARD", "missing": "&nbsp;", "noCount": true}, "score": {"earned": 93, "total": 100}, "title": "TEST 1"}}
  ],
  banner: [
    [["PC1", "PR1", "PC2", "PR2", "QC1", "Q1", "PC3", "PR3", "PC4", "PR4", "QC2", "Q2", "SE1", "S1", "PC5", "PR5", "PC6", "PR6", "QC3", "Q3", "PC7", "PR7", "PC8", "PR8", "QC4", "Q4", "SE2", "S2"]],
    [["S1", "S2"]],
    [["PR1", "C1", "MP1", "PC2", "PR2", "C2", "MP2", "PC3", "PR3", "C3", "MP3", "SE1", "S1", "PC4", "PR4", "C4", "MP4", "PC5", "PR5", "C5", "MP5", "PC6", "PR6", "C6", "MP6", "SE2", "S2", "AV"]]
  ],
  cat: [
    {"assignments": [], "category": "PE", "score": {"earned": 100, "total": 100}, "weight": []},
    {"assignments": [], "category": "Major", "score": [], "weight": []},
    {"assignments": [], "category": "Homework", "score": [], "weight": []}
  ],
  course: [
    {"courses": {"name": "IND STUDY TECH APP 1", "terms": "1 - 4", "scores": []}},
    {"courses": {"name": "CHEMISTRY 1 PreAP-GT", "scores": [], "terms": "1 - 6"}},
    {"courses": {"name": "ENGLISH 3", "scores": [], "terms": "1 - 2"}},
    {"courses": {"name": "ATH-CC-B 1A", "scores": [], "terms": "1 - 3"}},
    {"courses": {"name": "ENGLISH 1 PreAP", "scores": [], "terms": "1 - 3"}},
    {"courses": {"name": "WORLD GEOG PreA", "scores": [], "terms": "1 - 6"}}
  ],
  lit: [
    {"score": {"earned": 1000, "lit": "Q2", "total": 1000}, "weight": {"lit": "Q2", "percent": 10}},
    {"score": {"earned": 275, "lit": "Q2", "total": 300}, "weight": {"lit": "Q2", "percent": 70}},
    {"score": {"earned": 995, "lit": "Q2", "total": 1000}, "weight": {"lit": "Q2", "percent": 40}},
  ],
  strip: [
    ["99", "E", "98", null, "98", "E", "95", null, "100", "E", "100", "99", "98", null, "89", "E", "100", null, "100", "E", "100", null, "99", "E", "100", "X", "100", null],
    ["85", "94"],
    [null, null, null, null, null, null, null, null, null, null, null, null, "100", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]
  ],
  year: [
    {"grade": 11, "year": "2017 - 2018", "courses": []},
    {"grade": 10, "year": "2016 - 2017", "courses": []},
    {"grade": 10, "year": "2016 - 2017", "courses": []}
  ]
}